updated action-runner script

diff --git a/.github/scripts/ppc64le/self-hosted-builder/fs/usr/bin/actions-runner b/.github/scripts/ppc64le/self-hosted-builder/fs/usr/bin/actions-runner
--- a/.github/scripts/ppc64le/self-hosted-builder/fs/usr/bin/actions-runner
+++ b/.github/scripts/ppc64le/self-hosted-builder/fs/usr/bin/actions-runner
@@ -2,13 +2,45 @@
 
 set -e -u
 
+trap cleanup EXIT
+
+token_file=registration-token.json
+
+# Function to clean up and unregister the runner
+cleanup() {
+    echo "Cleaning up temporary files..."
+    [ -f "$token_file" ] && rm -f "$token_file"
+    [ -f "runner-id.json" ] && rm -f "runner-id.json"
+
+    echo "Unregistering the runner from GitHub..."
+    ACCESS_TOKEN="$(cat /run/runner_secret)"
+    runner_id=$(curl -s \
+        -H "Accept: application/vnd.github.v3+json" \
+        -H "Authorization: Bearer ${ACCESS_TOKEN}" \
+        "https://api.github.com/repos/${OWNER}/${REPO}/actions/runners" | \
+        jq --raw-output '.runners[] | select(.name=="'"${NAME}"'") | .id')
+
+    if [ -n "$runner_id" ]; then
+        curl -s \
+            -X DELETE \
+            -H "Accept: application/vnd.github.v3+json" \
+            -H "Authorization: Bearer ${ACCESS_TOKEN}" \
+            "https://api.github.com/repos/${OWNER}/${REPO}/actions/runners/$runner_id"
+        echo "Runner unregistered successfully."
+    else
+        echo "Warning: Runner ID for ${NAME} not found. It may already be removed."
+    fi
+
+    unset ACCESS_TOKEN runner_id
+}
+
 # Fetch GitHub access token
 if [ ! -f /run/runner_secret ]; then
     echo "Error: Access token file not found at /run/runner_secret."
     exit 1
 fi
 
-token_file=registration-token.json
+
 
 ACCESS_TOKEN="$(cat /run/runner_secret)"
 
@@ -37,7 +69,7 @@ registration_token=$(jq --raw-output .token "$token_file")
         --labels self-hosted,linux.ppc64le
 
 unset registration_token
-rm -f "$token_file"
+#rm -f "$token_file"
 
 # enter into python virtual environment.
 # build workflows use "python -m pip install ...",
@@ -46,24 +78,5 @@ rm -f "$token_file"
 
 # Run one job.
 ./run.sh
-
-# Unregister runner after job completion
-echo "Unregistering runner from GitHub..."
-runner_id=$(curl -s \
-    -H "Accept: application/vnd.github.v3+json" \
-    -H "Authorization: Bearer $(cat /run/runner_secret)" \
-    "https://api.github.com/repos/${OWNER}/${REPO}/actions/runners" | \
-    jq --raw-output '.runners[] | select(.name=="'"${NAME}"'") | .id')
-
-if [ -n "$runner_id" ]; then
-    curl -s \
-        -X DELETE \
-        -H "Accept: application/vnd.github.v3+json" \
-        -H "Authorization: Bearer $(cat /run/runner_secret)" \
-        "https://api.github.com/repos/${OWNER}/${REPO}/actions/runners/$runner_id"
-    echo "Runner unregistered successfully."
-else
-    echo "Warning: Runner ID for ${NAME} not found. It may already be removed."
-fi
 
 echo "Ephemeral runner workflow completed."
