nightly build changes except 313

diff --git a/.ci/docker/manywheel/Dockerfile_ppc64le b/.ci/docker/manywheel/Dockerfile_ppc64le
--- a/.ci/docker/manywheel/Dockerfile_ppc64le
+++ b/.ci/docker/manywheel/Dockerfile_ppc64le
@@ -90,8 +90,8 @@ FROM patchelf as python
 COPY manywheel/build_scripts /build_scripts
 ADD ./common/install_cpython.sh /build_scripts/install_cpython.sh
 ENV SSL_CERT_FILE=
-#RUN bash build_scripts/build.sh && rm -r build_scripts
-RUN bash build_scripts/build.sh || (echo "Checksum verification failed!" && exit 1)
+RUN bash build_scripts/build.sh && rm -r build_scripts
+#RUN bash build_scripts/build.sh || (echo "Checksum verification failed!" && exit 1)
 
 FROM base as final
 COPY --from=python             /opt/python                           /opt/python
