updated build.sh for ppc

diff --git a/.ci/docker/manywheel/Dockerfile_ppc64le b/.ci/docker/manywheel/Dockerfile_ppc64le
--- a/.ci/docker/manywheel/Dockerfile_ppc64le
+++ b/.ci/docker/manywheel/Dockerfile_ppc64le
@@ -7,45 +7,45 @@ ENV LANGUAGE=C.UTF-8
 
 # Installed needed OS packages. This is to support all
 # the binary builds (torch, vision, audio, text, data)
-RUN apt update ; apt upgrade -y
-RUN apt install -y \
-  build-essential \
-  autoconf \
-  automake \
-  bzip2 \
-  curl \
-  diffutils \
-  file \
-  git \
-  make \
-  patch \
-  perl \
-  unzip \
-  util-linux \
-  wget \
-  which \
-  xz-utils \
-  less \
-  zstd \
-  cmake \
-  python3 \
-  python3-dev \
-  python3-setuptools \
-  python3-yaml \
-  python3-typing-extensions \
-  libblas-dev \
-  libopenblas-dev \
-  liblapack-dev \
-  libatlas-base-dev \
-  linux-headers-generic \
-  zlib1g-dev \
-  libbz2-1.0 \
-  libncurses5-dev \
-  libsqlite3-dev \
-  libdb-dev \
-  libpcap-dev \
-  liblzma-dev \
-  libffi-dev || echo "Some packages could not be installed but are non-critical."
+RUN apt update && apt upgrade -y && \
+  apt install -y \
+    build-essential \
+    autoconf \
+    automake \
+    bzip2 \
+    curl \
+    diffutils \
+    file \
+    git \
+    make \
+    patch \
+    perl \
+    unzip \
+    util-linux \
+    wget \
+    which \
+    xz-utils \
+    less \
+    zstd \
+    cmake \
+    python3 \
+    python3-dev \
+    python3-setuptools \
+    python3-yaml \
+    python3-typing-extensions \
+    libblas-dev \
+    libopenblas-dev \
+    liblapack-dev \
+    libatlas-base-dev \
+    linux-headers-generic \
+    zlib1g-dev \
+    libbz2-1.0 \
+    libncurses5-dev \
+    libsqlite3-dev \
+    libdb-dev \
+    libpcap-dev \
+    liblzma-dev \
+    libffi-dev || echo "Some packages could not be installed but are non-critical."
 
 # Handle linux-headers installation gracefully
 RUN apt-get update && \
@@ -57,6 +57,8 @@ RUN apt-get update && \
 # Which causes version check to fail, as pytorch repo is bind-mounted into the image
 # Override this behaviour by treating every folder as safe
 # For more details see https://github.com/pytorch/pytorch/issues/78659#issuecomment-1144107327
+# Confirm git installation to prevent further issues
+RUN git --version || (echo "Git installation failed!" && exit 1)
 RUN git config --global --add safe.directory "*"
 
 FROM base as openssl
