using env logic for token1

diff --git a/.github/scripts/ppc64le-ci/self-hosted-builder/fs/usr/bin/actions-runner b/.github/scripts/ppc64le-ci/self-hosted-builder/fs/usr/bin/actions-runner
--- a/.github/scripts/ppc64le-ci/self-hosted-builder/fs/usr/bin/actions-runner
+++ b/.github/scripts/ppc64le-ci/self-hosted-builder/fs/usr/bin/actions-runner
@@ -12,10 +12,10 @@ fi
 token_file=registration-token.json
 
 # Fetch GitHub access token
-if [ ! -f /run/runner_secret ]; then
-    echo "Error: Access token file not found at /run/runner_secret."
-    exit 1
-fi
+# if [ ! -f /run/runner_secret ]; then
+#     echo "Error: Access token file not found at /run/runner_secret."
+#     exit 1
+# fi
 
 
 #ACCESS_TOKEN="$(cat /run/runner_secret)"
