yml changes

diff --git a/.github/workflows/_linux-build.yml b/.github/workflows/_linux-build.yml
--- a/.github/workflows/_linux-build.yml
+++ b/.github/workflows/_linux-build.yml
@@ -244,40 +244,28 @@ jobs:
           # detached container should get cleaned up by teardown_ec2_linux
           # Used for JENKINS_USER and DOCKER_SHELL_CMD, which can be empty
           # shellcheck disable=SC2086
-          container_name=$(docker run \
+          container_name=$(podman run \
             --cgroup-manager=cgroupfs \
             --cgroupns=private \
-            -e BUILD_ENVIRONMENT \
-            -e MAX_JOBS="$(nproc --ignore=2)" \
-            -e AWS_DEFAULT_REGION \
-            -e PR_NUMBER \
-            -e SHA1 \
-            -e BRANCH \
-            -e SCCACHE_BUCKET \
-            -e SCCACHE_REGION \
-            -e XLA_CUDA \
-            -e XLA_CLANG_CACHE_S3_BUCKET_NAME \
-            -e SKIP_SCCACHE_INITIALIZATION=1 \
-            -e TORCH_CUDA_ARCH_LIST \
-            -e PR_LABELS \
-            -e OUR_GITHUB_JOB_ID \
-            -e HUGGING_FACE_HUB_TOKEN \
-            -e SCRIBE_GRAPHQL_ACCESS_TOKEN \
-            -e USE_SPLIT_BUILD \
+            --pid=host \
             --memory="${TOTAL_AVAILABLE_MEMORY_IN_GB%.*}g" \
             --memory-swap="${TOTAL_MEMORY_WITH_SWAP}g" \
-            --env-file="/tmp/github_env_${GITHUB_RUN_ID}" \
             --security-opt seccomp=unconfined \
             --cap-add=SYS_PTRACE \
             --tty \
-            --detach \
             --privileged \
-            ${JENKINS_USER} \
+            --detach \
             -v "${GITHUB_WORKSPACE}:/var/lib/jenkins/workspace" \
             -w /var/lib/jenkins/workspace \
             "${USED_IMAGE}" \
             ${DOCKER_SHELL_CMD}
           )
+
+          # Check if container started successfully
+          if [ -z "$container_name" ]; then
+            echo "Container failed to start"
+            exit 1
+          fi
           podman exec -t "${container_name}" sh -c '.ci/pytorch/build.sh'
 
           END_TIME=$(date +%s)
