dockerfile name in yml

diff --git a/.github/workflows/ppc64le.yml b/.github/workflows/ppc64le.yml
--- a/.github/workflows/ppc64le.yml
+++ b/.github/workflows/ppc64le.yml
@@ -31,11 +31,11 @@ jobs:
 
       - name: Debug .git directory inside container
         run: |
-          docker run --rm -v "$(pwd)/pytorch/pytorch:/workspace/pytorch" pytorch-ppc64le:ubi9.3 bash -c "ls -la /workspace/pytorch/.git || echo '.git directory not found'"
+          docker run --rm -v "$(pwd):/workspace/pytorch" pytorch-ppc64le:ubi9.3 bash -c "ls -la /workspace/pytorch/.git || echo '.git directory not found'"
       
       - name: Debug ownership inside container
         run: |
-          docker run --rm -v "$(pwd)/pytorch:/workspace/pytorch" pytorch-ppc64le:ubi9.3 bash -c "
+          docker run --rm -v "$(pwd):/workspace/pytorch" pytorch-ppc64le:ubi9.3 bash -c "
             ls -ld /workspace/pytorch;
             ls -ld /workspace/pytorch/.git;
             whoami"
@@ -43,7 +43,7 @@ jobs:
       
       - name: Run Docker container and execute build script
         run: |
-          docker run --rm -v "$(pwd)/pytorch:/workspace/pytorch/pytorch" pytorch-ppc64le:ubi9.3 bash -c "
+          docker run --rm -u $(id -u):$(id -g) -v "$(pwd):/workspace/pytorch/pytorch" pytorch-ppc64le:ubi9.3 bash -c "
             export GIT_DISCOVERY_ACROSS_FILESYSTEM=1 &&
             git config --global --add safe.directory /workspace/pytorch &&
             git -C /workspace/pytorch submodule deinit --all --force &&
